name: Checkstyle
on:
  push:
    branches-ignore: [master]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master]
jobs:
  build:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: 'checkstyle.xml'
          reporter: 'github-check'
          tool_name: 'checkstyle'