name: Checkstyle
on:
  pull_request

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: 'checkstyle.xml'
          reporter: 'github-pr-check'
          level: 'warning'
          fail_on_error: 'true'
          tool_name: 'checkstyle'